name: raidalarm
description: "Raid Alarm - Smart security application that instantly detects attack notifications and warns you with loud alarms, fake calls, and vibration. Works 24/7 in the background even when your phone is locked."
publish_to: "none"

version: 2.0.4+61

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  vibration: ^3.1.4
  lucide_icons_flutter: ^3.1.9
  json_annotation: ^4.9.0
  audioplayers: ^6.1.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  sqflite: ^2.4.2
  path: ^1.9.0
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.2
  go_router: ^17.0.1
  http: ^1.2.0
  connectivity_plus: ^6.1.0
  internet_connection_checker: ^3.0.1
  easy_localization: ^3.0.8
  flutter_local_notifications: ^19.5.0
  flutter_screenutil: ^5.9.0
  flutter_dotenv: ^6.0.0
  external_app_launcher: ^4.0.3
  android_intent_plus: ^5.2.0
  onesignal_flutter: ^5.3.5
  adapty_flutter: ^3.15.3
  image_picker: ^1.0.7
  webview_flutter: ^4.10.0
  file_picker: ^10.3.8
  quick_actions: ^1.1.0
  in_app_review: ^2.0.11
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  protobuf: ^6.0.0
  web_socket_channel: ^3.0.0
  device_info_plus: ^10.1.0
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  uuid: ^4.4.0
  fixnum: ^1.1.0
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  isar_generator: ^3.1.0
  analyzer: ^5.13.0

flutter:
  uses-material-design: true

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Geist-Black.ttf
          weight: 900

  assets:
    - assets/logo/
    - assets/translations/
    - assets/audio/
    - assets/images/jpg/
    - assets/images/jpg/cctv/
    - assets/images/png/
    - assets/images/png/ingame/tea/berry/
    - assets/images/png/ingame/tea/basic-tea/
    - assets/images/png/ingame/tea/advanced-tea/
    - assets/images/png/ingame/tea/pure-tea/
    - assets/images/png/ingame/build/
    - assets/images/png/ingame/damage-items/
    - assets/images/png/ingame/items/
    - assets/images/png/ingame/pairing/
    - assets/images/png/ingame/traps/
    - assets/images/png/ingame/doors/
    - assets/images/png/ingame/diesel-calculator/
    - assets/images/png/ingame/weapons/
    - assets/images/png/ingame/weapons/automatic/
    - assets/images/png/ingame/weapons/launcher/
    - assets/images/png/ingame/weapons/others/
    - assets/images/png/ingame/weapons/melee/
    - assets/images/png/ingame/weapons/semi-automatic/
    - assets/images/png/ingame/weapons/shotgun/
    - assets/
    - .env
